# Generated by mm-ffi-codegen from the engine's layout registry. DO NOT EDIT.
#
# Every class here mirrors a Rust type's exact `#[repr(C)]` layout -- sizes, alignments and
# field offsets are the ones the engine measured, and `tools/tests/` checks that `ctypes`
# reproduces them. Regenerate with `mm-cli run` after any engine change; this file is
# gitignored precisely so it cannot go stale.
#
# The wire layer and the friendly surface on top of it are both here: `StateOption` fields
# read as `Optional[T]`, `BotArray` is a sequence over its live slots, `TeamPair` and
# `GameState.fleets()` index by `Team`, and a data enum has a constructor per variant. The
# raw `_fields_` entry behind a property keeps its name with a leading underscore.
#
# `core/channel.py` holds what a registry cannot describe: the channel loop and the
# navigation wrappers.

from .bindings import *  # noqa: F401,F403
