# Generated by mm-ffi-codegen from the engine's layout registry. DO NOT EDIT.
#
# Every class here mirrors a Rust type's exact `#[repr(C)]` layout -- sizes, alignments and
# field offsets are the ones the engine measured, and `tools/tests/` checks that `ctypes`
# reproduces them. Regenerate with `mm-cli run` after any engine change; this file is
# gitignored precisely so it cannot go stale.
#
# The wire layer and the friendly surface on top of it are both here: `StateOption` fields
# read as `Optional[T]`, `BotArray` is a sequence over its live slots, `TeamPair` and
# `GameState.fleets()` index by `Team`, and a data enum has a constructor per variant. The
# raw `_fields_` entry behind a property keeps its name with a leading underscore.
#
# `core/channel.py` holds what a registry cannot describe: the channel loop and the
# navigation wrappers.

from __future__ import annotations

import ctypes
import enum
import math
import os
import pathlib
from typing import Generic, Iterator, Optional, TypeVar

# -----------------------------------------------------------------------------------
# helpers the friendly surface is built from
# -----------------------------------------------------------------------------------

_T = TypeVar("_T")


class _Pair(Generic[_T]):
    """Two attributes of one struct, indexed by `Team`.

    `GameState` stores its fleets, deposits and fabricators as `*_me`/`*_other` field pairs
    rather than as a `TeamPair`, because a `TeamPair<BotArray>` would be one struct the
    engine's `Diff` could not describe per fleet. This is the `TeamPair<&T>` that Rust's
    `GameState::fleets()` hands back: a view, not a copy, so writing through it is writing
    through to the state.
    """

    __slots__ = ("_owner", "_me_attr", "_other_attr")

    def __init__(self, owner: object, me_attr: str, other_attr: str) -> None:
        self._owner = owner
        self._me_attr = me_attr
        self._other_attr = other_attr

    def _attr(self, team: Team) -> str:
        return self._me_attr if team == Team.Me else self._other_attr

    def __getitem__(self, team: Team) -> _T:
        return getattr(self._owner, self._attr(team))

    def __setitem__(self, team: Team, value: _T) -> None:
        setattr(self._owner, self._attr(team), value)

    @property
    def me(self) -> _T:
        return self[Team.Me]

    @property
    def other(self) -> _T:
        return self[Team.Other]

    def __iter__(self) -> Iterator[_T]:
        yield self.me
        yield self.other

    def __repr__(self) -> str:
        return f"_Pair(me={self.me!r}, other={self.other!r})"

# -----------------------------------------------------------------------------------
# constants
# -----------------------------------------------------------------------------------
BOTS_MAX = 32
COMPUTE_BANK_TICKS = 500000
COMPUTE_REFILL_TICKS = 600
MAP_SIZE = 32
MM_CLOSED = 1
MM_IO = 4
MM_MALFORMED = 3
MM_OK = 0
MM_PANIC = 5
MM_TIMEOUT = 2
PAYLOAD_PATH_LEN = 7

# -----------------------------------------------------------------------------------
# wire types, in dependency order
# -----------------------------------------------------------------------------------

class BotClass(enum.IntEnum):
    """`BotClass` -- a `u8` on the wire. `IntEnum`, so a field read back as an
    `int` compares equal to a member without conversion."""
    Battle = 0
    Healer = 1
    Extractor = 2

BotClass_t = ctypes.c_uint8

class BotConfig(ctypes.Structure):
    """`BotConfig` -- 60 bytes, align 4."""
    radius: float
    speed: float
    health: float
    turn_speed: float
    blaster_cooldown: int
    blaster_range: float
    blaster_damage: float
    heal_per_tick: float
    extract_rate: float
    base_invulnerability_ticks: int
    base_blaster_splash_radius: float
    base_heal_range: float
    base_heal_arc_deg: float
    heal_stack_cap: float
    base_extract_range: float
    _fields_ = [
        ("radius", ctypes.c_float),
        ("speed", ctypes.c_float),
        ("health", ctypes.c_float),
        ("turn_speed", ctypes.c_float),
        ("blaster_cooldown", ctypes.c_uint32),
        ("blaster_range", ctypes.c_float),
        ("blaster_damage", ctypes.c_float),
        ("heal_per_tick", ctypes.c_float),
        ("extract_rate", ctypes.c_float),
        ("base_invulnerability_ticks", ctypes.c_uint32),
        ("base_blaster_splash_radius", ctypes.c_float),
        ("base_heal_range", ctypes.c_float),
        ("base_heal_arc_deg", ctypes.c_float),
        ("heal_stack_cap", ctypes.c_float),
        ("base_extract_range", ctypes.c_float),
    ]

class FabricatorConfig(ctypes.Structure):
    """`FabricatorConfig` -- 12 bytes, align 4."""
    interval: int
    rush_cost: float
    starting_tokens: float
    _fields_ = [
        ("interval", ctypes.c_uint32),
        ("rush_cost", ctypes.c_float),
        ("starting_tokens", ctypes.c_float),
    ]

class FabricatorState(ctypes.Structure):
    """`FabricatorState` -- 8 bytes, align 4."""
    tokens: float
    next_bot_creation: int
    _fields_ = [
        ("tokens", ctypes.c_float),
        ("next_bot_creation", ctypes.c_uint32),
    ]

class MapTile(enum.IntEnum):
    """`MapTile` -- a `u8` on the wire. `IntEnum`, so a field read back as an
    `int` compares equal to a member without conversion."""
    Empty = 0
    Wall = 1

MapTile_t = ctypes.c_uint8

class PayloadConfig(ctypes.Structure):
    """`PayloadConfig` -- 12 bytes, align 4."""
    radius: float
    capture_radius: float
    speed: float
    _fields_ = [
        ("radius", ctypes.c_float),
        ("capture_radius", ctypes.c_float),
        ("speed", ctypes.c_float),
    ]

class _SpecialAction_Battle(ctypes.Structure):
    """`SpecialAction::Battle` -- the payload only; the tag lives in `SpecialAction`."""
    fire: bool
    _fields_ = [
        ("fire", ctypes.c_bool),
    ]

class _SpecialAction_Healer(ctypes.Structure):
    """`SpecialAction::Healer` -- the payload only; the tag lives in `SpecialAction`."""
    fire: bool
    target: int
    _fields_ = [
        ("fire", ctypes.c_bool),
        ("target", ctypes.c_uint8),
    ]

class _SpecialAction_Extractor(ctypes.Structure):
    """`SpecialAction::Extractor` -- the payload only; the tag lives in `SpecialAction`."""
    mine: bool
    _fields_ = [
        ("mine", ctypes.c_bool),
    ]

class _SpecialAction_Payload(ctypes.Union):
    battle: _SpecialAction_Battle
    healer: _SpecialAction_Healer
    extractor: _SpecialAction_Extractor
    _fields_ = [
        ("battle", _SpecialAction_Battle),
        ("healer", _SpecialAction_Healer),
        ("extractor", _SpecialAction_Extractor),
    ]

class SpecialActionTag(enum.IntEnum):
    Battle = 0
    Healer = 1
    Extractor = 2

class SpecialAction(ctypes.Structure):
    """`SpecialAction` -- `#[repr(u8, C)]`: a `u8` tag at 0, payload at 1.
    3 bytes, align 1. Read `tag` against `SpecialActionTag`, then the matching
    member of `payload`."""
    tag: int
    payload: _SpecialAction_Payload
    _fields_ = [
        ("tag", ctypes.c_uint8),
        ("payload", _SpecialAction_Payload),
    ]

    @property
    def variant(self) -> SpecialActionTag:
        return SpecialActionTag(self.tag)

    def __repr__(self) -> str:
        return f"SpecialAction.{SpecialActionTag(self.tag).name}"

    @classmethod
    def Battle(cls, fire: bool) -> SpecialAction:
        """`SpecialAction::Battle`, tag and payload set together."""
        out = cls()
        out.tag = SpecialActionTag.Battle
        payload = out.payload.battle
        payload.fire = fire
        return out

    @property
    def as_battle(self) -> Optional[_SpecialAction_Battle]:
        """The `Battle` payload, or `None` if this value is a different variant."""
        if self.tag != SpecialActionTag.Battle:
            return None
        return self.payload.battle

    @classmethod
    def Healer(cls, fire: bool, target: int) -> SpecialAction:
        """`SpecialAction::Healer`, tag and payload set together."""
        out = cls()
        out.tag = SpecialActionTag.Healer
        payload = out.payload.healer
        payload.fire = fire
        payload.target = target
        return out

    @property
    def as_healer(self) -> Optional[_SpecialAction_Healer]:
        """The `Healer` payload, or `None` if this value is a different variant."""
        if self.tag != SpecialActionTag.Healer:
            return None
        return self.payload.healer

    @classmethod
    def Extractor(cls, mine: bool) -> SpecialAction:
        """`SpecialAction::Extractor`, tag and payload set together."""
        out = cls()
        out.tag = SpecialActionTag.Extractor
        payload = out.payload.extractor
        payload.mine = mine
        return out

    @property
    def as_extractor(self) -> Optional[_SpecialAction_Extractor]:
        """The `Extractor` payload, or `None` if this value is a different variant."""
        if self.tag != SpecialActionTag.Extractor:
            return None
        return self.payload.extractor

class _StateOption_BotId_None(ctypes.Structure):
    """`StateOption<BotId>::None` -- the payload only; the tag lives in `StateOption_BotId`."""
    _fields_ = []

class _StateOption_BotId_Some(ctypes.Structure):
    """`StateOption<BotId>::Some` -- the payload only; the tag lives in `StateOption_BotId`."""
    f0: int
    _fields_ = [
        ("f0", ctypes.c_uint8),
    ]

class _StateOption_BotId_Payload(ctypes.Union):
    none: _StateOption_BotId_None
    some: _StateOption_BotId_Some
    _fields_ = [
        ("none", _StateOption_BotId_None),
        ("some", _StateOption_BotId_Some),
    ]

class StateOption_BotIdTag(enum.IntEnum):
    None_ = 0
    Some = 1

class StateOption_BotId(ctypes.Structure):
    """`StateOption<BotId>` -- `#[repr(u8, C)]`: a `u8` tag at 0, payload at 1.
    2 bytes, align 1. Read `tag` against `StateOption_BotIdTag`, then the matching
    member of `payload`."""
    tag: int
    payload: _StateOption_BotId_Payload
    _fields_ = [
        ("tag", ctypes.c_uint8),
        ("payload", _StateOption_BotId_Payload),
    ]

    @property
    def option(self) -> Optional[int]:
        """`StateOption<u8>` as Python sees it. Rust's `StateOption::option`."""
        if self.tag != StateOption_BotIdTag.Some:
            return None
        return self.payload.some.f0

    @classmethod
    def of(cls, value: Optional[int]) -> StateOption_BotId:
        """The wrapper around `value`, or the `None` variant. Rust's `From<Option<T>>`."""
        out = cls()
        if value is None:
            out.tag = StateOption_BotIdTag.None_
        else:
            out.tag = StateOption_BotIdTag.Some
            out.payload.some.f0 = value
        return out

    def __repr__(self) -> str:
        return repr(self.option)

class Team(enum.IntEnum):
    """`Team` -- a `u8` on the wire. `IntEnum`, so a field read back as an
    `int` compares equal to a member without conversion."""
    Me = 0
    Other = 1

    def other_team(self) -> Team:
        return Team.Other if self is Team.Me else Team.Me

Team_t = ctypes.c_uint8

class TeamPair_u32(ctypes.Structure):
    """`TeamPair<u32>` -- 8 bytes, align 4."""
    me: int
    other: int
    _fields_ = [
        ("me", ctypes.c_uint32),
        ("other", ctypes.c_uint32),
    ]

    def __getitem__(self, team: Team) -> int:
        return self.me if team == Team.Me else self.other

    def __setitem__(self, team: Team, value: int) -> None:
        if team == Team.Me:
            self.me = value
        else:
            self.other = value

    def __iter__(self) -> Iterator[int]:
        yield self.me
        yield self.other

class Vec2(ctypes.Structure):
    """`Vec2` -- 8 bytes, align 4."""
    x: float
    y: float
    _fields_ = [
        ("x", ctypes.c_float),
        ("y", ctypes.c_float),
    ]

    def __init__(self, x: float = 0.0, y: float = 0.0) -> None:
        """Defaulted, so `Vec2()` is the zero vector -- Rust's `Vec2::ZERO`."""
        super().__init__(x, y)

    @classmethod
    def from_angle_rad(cls, angle_rad: float) -> Vec2:
        return cls(math.cos(angle_rad), math.sin(angle_rad))

    @classmethod
    def from_angle_deg(cls, angle_deg: float) -> Vec2:
        return cls.from_angle_rad(math.radians(angle_deg))

    def dot(self, other: Vec2) -> float:
        return self.x * other.x + self.y * other.y

    def norm_sq(self) -> float:
        return self.x * self.x + self.y * self.y

    def norm(self) -> float:
        return math.sqrt(self.norm_sq())

    def angle_rad(self) -> float:
        return math.atan2(self.y, self.x)

    def angle_deg(self) -> float:
        return math.degrees(self.angle_rad())

    def normalize_or_zero(self) -> Vec2:
        """A unit vector in the same direction, or `(0, 0)` if there is no direction."""
        n = self.norm()
        return Vec2(0.0, 0.0) if n == 0.0 else Vec2(self.x / n, self.y / n)

    def rotate_rad(self, angle_rad: float) -> Vec2:
        c, s = math.cos(angle_rad), math.sin(angle_rad)
        return Vec2(self.x * c - self.y * s, self.x * s + self.y * c)

    def rotate_deg(self, angle_deg: float) -> Vec2:
        return self.rotate_rad(math.radians(angle_deg))

    def dist_sq(self, other: Vec2) -> float:
        return (self - other).norm_sq()

    def dist(self, other: Vec2) -> float:
        return (self - other).norm()

    def __add__(self, other: Vec2) -> Vec2:
        return Vec2(self.x + other.x, self.y + other.y)

    def __sub__(self, other: Vec2) -> Vec2:
        return Vec2(self.x - other.x, self.y - other.y)

    def __mul__(self, scalar: float) -> Vec2:
        return Vec2(self.x * scalar, self.y * scalar)

    def __rmul__(self, scalar: float) -> Vec2:
        return self.__mul__(scalar)

    def __truediv__(self, scalar: float) -> Vec2:
        return Vec2(self.x / scalar, self.y / scalar)

    def __neg__(self) -> Vec2:
        return Vec2(-self.x, -self.y)

    def __eq__(self, other: object) -> bool:
        return isinstance(other, Vec2) and self.x == other.x and self.y == other.y

    def __hash__(self) -> int:
        return hash((self.x, self.y))

    def __repr__(self) -> str:
        return f"Vec2({self.x}, {self.y})"

class Deposit(ctypes.Structure):
    """`Deposit` -- 16 bytes, align 4."""
    pos: Vec2
    extractors: TeamPair_u32
    _fields_ = [
        ("pos", Vec2),
        ("extractors", TeamPair_u32),
    ]

class DepositConfig(ctypes.Structure):
    """`DepositConfig` -- 16 bytes, align 4."""
    pos: Vec2
    radius: float
    extractor_cap: int
    _fields_ = [
        ("pos", Vec2),
        ("radius", ctypes.c_float),
        ("extractor_cap", ctypes.c_uint8),
    ]

class GameConfig(ctypes.Structure):
    """`GameConfig` -- 1188 bytes, align 4."""
    max_ticks: int
    endgame_ticks: int
    bot: BotConfig
    payload: PayloadConfig
    payload_path: ctypes.Array[Vec2]
    deposit: DepositConfig
    fabricator: FabricatorConfig
    map: ctypes.Array[ctypes.Array[int]]
    _fields_ = [
        ("max_ticks", ctypes.c_uint32),
        ("endgame_ticks", ctypes.c_uint32),
        ("bot", BotConfig),
        ("payload", PayloadConfig),
        ("payload_path", Vec2 * PAYLOAD_PATH_LEN),
        ("deposit", DepositConfig),
        ("fabricator", FabricatorConfig),
        ("map", MapTile_t * MAP_SIZE * MAP_SIZE),
    ]

class HandshakeRequest(ctypes.Structure):
    """`HandshakeRequest` -- 1192 bytes, align 4."""
    team: int
    config: GameConfig
    _fields_ = [
        ("team", Team_t),
        ("config", GameConfig),
    ]

class MoveAction(ctypes.Structure):
    """`MoveAction` -- 8 bytes, align 4."""
    direction: Vec2
    _fields_ = [
        ("direction", Vec2),
    ]

class _StateOption_Team_None(ctypes.Structure):
    """`StateOption<Team>::None` -- the payload only; the tag lives in `StateOption_Team`."""
    _fields_ = []

class _StateOption_Team_Some(ctypes.Structure):
    """`StateOption<Team>::Some` -- the payload only; the tag lives in `StateOption_Team`."""
    f0: int
    _fields_ = [
        ("f0", Team_t),
    ]

class _StateOption_Team_Payload(ctypes.Union):
    none: _StateOption_Team_None
    some: _StateOption_Team_Some
    _fields_ = [
        ("none", _StateOption_Team_None),
        ("some", _StateOption_Team_Some),
    ]

class StateOption_TeamTag(enum.IntEnum):
    None_ = 0
    Some = 1

class StateOption_Team(ctypes.Structure):
    """`StateOption<Team>` -- `#[repr(u8, C)]`: a `u8` tag at 0, payload at 1.
    2 bytes, align 1. Read `tag` against `StateOption_TeamTag`, then the matching
    member of `payload`."""
    tag: int
    payload: _StateOption_Team_Payload
    _fields_ = [
        ("tag", ctypes.c_uint8),
        ("payload", _StateOption_Team_Payload),
    ]

    @property
    def option(self) -> Optional[Team]:
        """`StateOption<Team>` as Python sees it. Rust's `StateOption::option`."""
        if self.tag != StateOption_TeamTag.Some:
            return None
        return Team(self.payload.some.f0)

    @classmethod
    def of(cls, value: Optional[Team]) -> StateOption_Team:
        """The wrapper around `value`, or the `None` variant. Rust's `From<Option<T>>`."""
        out = cls()
        if value is None:
            out.tag = StateOption_TeamTag.None_
        else:
            out.tag = StateOption_TeamTag.Some
            out.payload.some.f0 = value
        return out

    def __repr__(self) -> str:
        return repr(self.option)

class _StateOption_Vec2_None(ctypes.Structure):
    """`StateOption<Vec2>::None` -- the payload only; the tag lives in `StateOption_Vec2`."""
    _fields_ = []

class _StateOption_Vec2_Some(ctypes.Structure):
    """`StateOption<Vec2>::Some` -- the payload only; the tag lives in `StateOption_Vec2`."""
    f0: Vec2
    _fields_ = [
        ("f0", Vec2),
    ]

class _StateOption_Vec2_Payload(ctypes.Union):
    none: _StateOption_Vec2_None
    some: _StateOption_Vec2_Some
    _fields_ = [
        ("none", _StateOption_Vec2_None),
        ("some", _StateOption_Vec2_Some),
    ]

class StateOption_Vec2Tag(enum.IntEnum):
    None_ = 0
    Some = 1

class StateOption_Vec2(ctypes.Structure):
    """`StateOption<Vec2>` -- `#[repr(u8, C)]`: a `u8` tag at 0, payload at 4.
    12 bytes, align 4. Read `tag` against `StateOption_Vec2Tag`, then the matching
    member of `payload`."""
    tag: int
    payload: _StateOption_Vec2_Payload
    _fields_ = [
        ("tag", ctypes.c_uint8),
        ("payload", _StateOption_Vec2_Payload),
    ]

    @property
    def option(self) -> Optional[Vec2]:
        """`StateOption<Vec2>` as Python sees it. Rust's `StateOption::option`."""
        if self.tag != StateOption_Vec2Tag.Some:
            return None
        return self.payload.some.f0

    @classmethod
    def of(cls, value: Optional[Vec2]) -> StateOption_Vec2:
        """The wrapper around `value`, or the `None` variant. Rust's `From<Option<T>>`."""
        out = cls()
        if value is None:
            out.tag = StateOption_Vec2Tag.None_
        else:
            out.tag = StateOption_Vec2Tag.Some
            out.payload.some.f0 = value
        return out

    def __repr__(self) -> str:
        return repr(self.option)

class _TurnAction_Direction(ctypes.Structure):
    """`TurnAction::Direction` -- the payload only; the tag lives in `TurnAction`."""
    power: float
    _fields_ = [
        ("power", ctypes.c_float),
    ]

class _TurnAction_TargetRotation(ctypes.Structure):
    """`TurnAction::TargetRotation` -- the payload only; the tag lives in `TurnAction`."""
    deg: float
    _fields_ = [
        ("deg", ctypes.c_float),
    ]

class _TurnAction_TargetPosition(ctypes.Structure):
    """`TurnAction::TargetPosition` -- the payload only; the tag lives in `TurnAction`."""
    pos: Vec2
    _fields_ = [
        ("pos", Vec2),
    ]

class _TurnAction_Payload(ctypes.Union):
    direction: _TurnAction_Direction
    target_rotation: _TurnAction_TargetRotation
    target_position: _TurnAction_TargetPosition
    _fields_ = [
        ("direction", _TurnAction_Direction),
        ("target_rotation", _TurnAction_TargetRotation),
        ("target_position", _TurnAction_TargetPosition),
    ]

class TurnActionTag(enum.IntEnum):
    Direction = 0
    TargetRotation = 1
    TargetPosition = 2

class TurnAction(ctypes.Structure):
    """`TurnAction` -- `#[repr(u8, C)]`: a `u8` tag at 0, payload at 4.
    12 bytes, align 4. Read `tag` against `TurnActionTag`, then the matching
    member of `payload`."""
    tag: int
    payload: _TurnAction_Payload
    _fields_ = [
        ("tag", ctypes.c_uint8),
        ("payload", _TurnAction_Payload),
    ]

    @property
    def variant(self) -> TurnActionTag:
        return TurnActionTag(self.tag)

    def __repr__(self) -> str:
        return f"TurnAction.{TurnActionTag(self.tag).name}"

    @classmethod
    def Direction(cls, power: float) -> TurnAction:
        """`TurnAction::Direction`, tag and payload set together."""
        out = cls()
        out.tag = TurnActionTag.Direction
        payload = out.payload.direction
        payload.power = power
        return out

    @property
    def as_direction(self) -> Optional[_TurnAction_Direction]:
        """The `Direction` payload, or `None` if this value is a different variant."""
        if self.tag != TurnActionTag.Direction:
            return None
        return self.payload.direction

    @classmethod
    def TargetRotation(cls, deg: float) -> TurnAction:
        """`TurnAction::TargetRotation`, tag and payload set together."""
        out = cls()
        out.tag = TurnActionTag.TargetRotation
        payload = out.payload.target_rotation
        payload.deg = deg
        return out

    @property
    def as_target_rotation(self) -> Optional[_TurnAction_TargetRotation]:
        """The `TargetRotation` payload, or `None` if this value is a different variant."""
        if self.tag != TurnActionTag.TargetRotation:
            return None
        return self.payload.target_rotation

    @classmethod
    def TargetPosition(cls, pos: Vec2) -> TurnAction:
        """`TurnAction::TargetPosition`, tag and payload set together."""
        out = cls()
        out.tag = TurnActionTag.TargetPosition
        payload = out.payload.target_position
        payload.pos = pos
        return out

    @property
    def as_target_position(self) -> Optional[_TurnAction_TargetPosition]:
        """The `TargetPosition` payload, or `None` if this value is a different variant."""
        if self.tag != TurnActionTag.TargetPosition:
            return None
        return self.payload.target_position

class BotAction(ctypes.Structure):
    """`BotAction` -- 24 bytes, align 4."""
    move_action: MoveAction
    turn_action: TurnAction
    special_action: SpecialAction
    self_destruct: bool
    _fields_ = [
        ("move_action", MoveAction),
        ("turn_action", TurnAction),
        ("special_action", SpecialAction),
        ("self_destruct", ctypes.c_bool),
    ]

class FleetAction(ctypes.Structure):
    """`FleetAction` -- 772 bytes, align 4."""
    bots: ctypes.Array[BotAction]
    fabricator_next: int
    rush_order: bool
    _fields_ = [
        ("bots", BotAction * BOTS_MAX),
        ("fabricator_next", BotClass_t),
        ("rush_order", ctypes.c_bool),
    ]

    @classmethod
    def new(cls) -> FleetAction:
        """The do-nothing action: no movement, no specials, no rush order.

        Every Rust default in this struct is its zero value, and `ctypes` zeroes a fresh
        instance, so this is `FleetAction()` -- kept as the name bots construct through, the
        way `FleetAction::new()` is on the Rust side.
        """
        return cls()

class _SpecialState_Battle(ctypes.Structure):
    """`SpecialState::Battle` -- the payload only; the tag lives in `SpecialState`."""
    next_fire_tick: int
    _shot: StateOption_Vec2
    _fields_ = [
        ("next_fire_tick", ctypes.c_uint32),
        ("_shot", StateOption_Vec2),
    ]

    @property
    def shot(self) -> Optional[Vec2]:
        return self._shot.option

    @shot.setter
    def shot(self, value: Optional[Vec2]) -> None:
        self._shot = StateOption_Vec2.of(value)

class _SpecialState_Healer(ctypes.Structure):
    """`SpecialState::Healer` -- the payload only; the tag lives in `SpecialState`."""
    _healing: StateOption_BotId
    _fields_ = [
        ("_healing", StateOption_BotId),
    ]

    @property
    def healing(self) -> Optional[int]:
        return self._healing.option

    @healing.setter
    def healing(self, value: Optional[int]) -> None:
        self._healing = StateOption_BotId.of(value)

class _SpecialState_Extractor(ctypes.Structure):
    """`SpecialState::Extractor` -- the payload only; the tag lives in `SpecialState`."""
    _extracting: StateOption_Team
    _fields_ = [
        ("_extracting", StateOption_Team),
    ]

    @property
    def extracting(self) -> Optional[Team]:
        return self._extracting.option

    @extracting.setter
    def extracting(self, value: Optional[Team]) -> None:
        self._extracting = StateOption_Team.of(value)

class _SpecialState_Payload(ctypes.Union):
    battle: _SpecialState_Battle
    healer: _SpecialState_Healer
    extractor: _SpecialState_Extractor
    _fields_ = [
        ("battle", _SpecialState_Battle),
        ("healer", _SpecialState_Healer),
        ("extractor", _SpecialState_Extractor),
    ]

class SpecialStateTag(enum.IntEnum):
    Battle = 0
    Healer = 1
    Extractor = 2

class SpecialState(ctypes.Structure):
    """`SpecialState` -- `#[repr(u8, C)]`: a `u8` tag at 0, payload at 4.
    20 bytes, align 4. Read `tag` against `SpecialStateTag`, then the matching
    member of `payload`."""
    tag: int
    payload: _SpecialState_Payload
    _fields_ = [
        ("tag", ctypes.c_uint8),
        ("payload", _SpecialState_Payload),
    ]

    @property
    def variant(self) -> SpecialStateTag:
        return SpecialStateTag(self.tag)

    def __repr__(self) -> str:
        return f"SpecialState.{SpecialStateTag(self.tag).name}"

    @classmethod
    def Battle(cls, next_fire_tick: int, shot: Optional[Vec2]) -> SpecialState:
        """`SpecialState::Battle`, tag and payload set together."""
        out = cls()
        out.tag = SpecialStateTag.Battle
        payload = out.payload.battle
        payload.next_fire_tick = next_fire_tick
        payload.shot = shot
        return out

    @property
    def as_battle(self) -> Optional[_SpecialState_Battle]:
        """The `Battle` payload, or `None` if this value is a different variant."""
        if self.tag != SpecialStateTag.Battle:
            return None
        return self.payload.battle

    @classmethod
    def Healer(cls, healing: Optional[int]) -> SpecialState:
        """`SpecialState::Healer`, tag and payload set together."""
        out = cls()
        out.tag = SpecialStateTag.Healer
        payload = out.payload.healer
        payload.healing = healing
        return out

    @property
    def as_healer(self) -> Optional[_SpecialState_Healer]:
        """The `Healer` payload, or `None` if this value is a different variant."""
        if self.tag != SpecialStateTag.Healer:
            return None
        return self.payload.healer

    @classmethod
    def Extractor(cls, extracting: Optional[Team]) -> SpecialState:
        """`SpecialState::Extractor`, tag and payload set together."""
        out = cls()
        out.tag = SpecialStateTag.Extractor
        payload = out.payload.extractor
        payload.extracting = extracting
        return out

    @property
    def as_extractor(self) -> Optional[_SpecialState_Extractor]:
        """The `Extractor` payload, or `None` if this value is a different variant."""
        if self.tag != SpecialStateTag.Extractor:
            return None
        return self.payload.extractor

class BotState(ctypes.Structure):
    """`BotState` -- 56 bytes, align 4."""
    id: int
    health: float
    pos: Vec2
    vel: Vec2
    angle: float
    turn_vel: float
    invulnerable_until_tick: int
    special: SpecialState
    _fields_ = [
        ("id", ctypes.c_uint8),
        ("health", ctypes.c_float),
        ("pos", Vec2),
        ("vel", Vec2),
        ("angle", ctypes.c_float),
        ("turn_vel", ctypes.c_float),
        ("invulnerable_until_tick", ctypes.c_uint32),
        ("special", SpecialState),
    ]

    @property
    def class_(self) -> BotClass:
        """This bot's class. Trailing underscore because `class` is a Python keyword.

        Resolved by variant *name* rather than by tag number: `SpecialStateTag` and
        `BotClass` happen to agree today, and a rename or reorder on one side should be a
        `KeyError` here rather than a silently wrong class.
        """
        return BotClass[SpecialStateTag(self.special.tag).name]

    @property
    def next_fire_tick(self) -> int:
        """The blaster's readiness tick, or `0` -- "ready now" -- for a class without one."""
        battle = self.special.as_battle
        return 0 if battle is None else battle.next_fire_tick

    @property
    def shot(self) -> Optional[Vec2]:
        """Impact point of this tick's shot; `None` on a tick this bot did not fire."""
        battle = self.special.as_battle
        return None if battle is None else battle.shot

    @property
    def healing(self) -> Optional[int]:
        """The ally this bot healed this tick, by id."""
        healer = self.special.as_healer
        return None if healer is None else healer.healing

    @property
    def extracting(self) -> Optional[Team]:
        """The deposit this bot extracted from this tick, named by its owning team."""
        extractor = self.special.as_extractor
        return None if extractor is None else extractor.extracting

class BotArray(ctypes.Structure):
    """`BotArray` -- 1828 bytes, align 4."""
    _len: int
    _mask: ctypes.Array[bool]
    _arr: ctypes.Array[BotState]
    _fields_ = [
        ("_len", ctypes.c_uint8),
        ("_mask", ctypes.c_bool * BOTS_MAX),
        ("_arr", BotState * BOTS_MAX),
    ]

    def __len__(self) -> int:
        """How many slots are live -- not `BOTS_MAX`."""
        return self._len

    def __iter__(self) -> Iterator[BotState]:
        """The live bots, in id order. Dead slots are skipped, not yielded as `None`."""
        for i in range(BOTS_MAX):
            if self._mask[i]:
                yield self._arr[i]

    def __getitem__(self, bot_id: int) -> Optional[BotState]:
        """The bot in slot `bot_id`, or `None` if that slot is dead or out of range.

        Rust's `Index` panics here and `get` returns an `Option`; Python has one syntax, so
        it is the forgiving one. `get` is kept as an alias for symmetry with the Rust name.
        """
        if not 0 <= bot_id < BOTS_MAX or not self._mask[bot_id]:
            return None
        return self._arr[bot_id]

    def get(self, bot_id: int) -> Optional[BotState]:
        return self[bot_id]

    def ids(self) -> Iterator[int]:
        """The live slot numbers, which are also the indices into `FleetAction.bots`."""
        return (i for i in range(BOTS_MAX) if self._mask[i])

    def is_full(self) -> bool:
        return self._len >= BOTS_MAX

class GameState(ctypes.Structure):
    """`GameState` -- 3712 bytes, align 4."""
    tick: int
    capture: float
    fleet_me: BotArray
    fleet_other: BotArray
    deposit_me: Deposit
    deposit_other: Deposit
    fabricator_me: FabricatorState
    fabricator_other: FabricatorState
    _fields_ = [
        ("tick", ctypes.c_uint32),
        ("capture", ctypes.c_float),
        ("fleet_me", BotArray),
        ("fleet_other", BotArray),
        ("deposit_me", Deposit),
        ("deposit_other", Deposit),
        ("fabricator_me", FabricatorState),
        ("fabricator_other", FabricatorState),
    ]

    def fleets(self) -> _Pair[BotArray]:
        return _Pair(self, "fleet_me", "fleet_other")

    def deposits(self) -> _Pair[Deposit]:
        return _Pair(self, "deposit_me", "deposit_other")

    def fabricators(self) -> _Pair[FabricatorState]:
        return _Pair(self, "fabricator_me", "fabricator_other")

    def payload_pos(self) -> Vec2:
        """Centre of the payload circle this tick. Its radius is `conf.payload.radius`."""
        out = (ctypes.c_float * 2)()
        mm_payload_pos(self.capture, out)
        return Vec2(out[0], out[1])


# -----------------------------------------------------------------------------------
# aliases
# -----------------------------------------------------------------------------------
BotId = ctypes.c_uint8
Map = MapTile_t * MAP_SIZE * MAP_SIZE

# -----------------------------------------------------------------------------------
# the C surface
# -----------------------------------------------------------------------------------


_LIBRARY_NAMES = (
    "libmm_python_native.so",
    "libmm_python_native.dylib",
    "mm_python_native.dll",
)


def _library_path() -> pathlib.Path:
    """The shared library this package's bindings were generated against.

    Two answers, because a bot runs in two very different shapes.

    `$MM_NATIVE_LIB` wins when set. A submitted bot is a zipapp, and `ctypes.CDLL` cannot
    open a path inside a `.pyz` -- nor is `__file__` a real path in there -- so the API's
    compile step drops the library beside `bot.pyz` and the `/out/bot` wrapper points this
    variable at it. Loading from a read-only bind mount is fine; `dlopen` only needs a path.

    Otherwise, the `mm-cli run` local loop: `native/target/release/`, resolved relative to
    this file rather than by name so a bot run from any working directory finds it.
    """
    override = os.environ.get("MM_NATIVE_LIB")
    if override:
        candidate = pathlib.Path(override)
        if not candidate.exists():
            raise FileNotFoundError(
                f"MM_NATIVE_LIB points at {candidate}, which does not exist"
            )
        return candidate

    root = pathlib.Path(__file__).resolve().parent.parent.parent / "native" / "target" / "release"
    for name in _LIBRARY_NAMES:
        candidate = root / name
        if candidate.exists():
            return candidate
    raise FileNotFoundError(
        f"no native library under {root} -- run mm-cli run first"
    )


_handle: object = None


def attach(handle: object) -> None:
    """Register the open channel, so the methods that need one can reach it.

    No generated method needs it today; it is the route a method on a state struct would
    take to reach the config the handshake captured, since it has no other way to the
    channel that delivered it. `core/channel.py` calls this once, at open, which is
    the same shape as `get_config()`: one match, one channel, one module global.
    """
    global _handle
    _handle = handle


def detach() -> None:
    global _handle
    _handle = None


def _require_handle() -> object:
    if _handle is None:
        raise RuntimeError(
            "no channel is attached -- open one through core.channel.EngineChannel "
            "before asking the engine about the match config"
        )
    return _handle


class MmChannel(ctypes.c_void_p):
    """Opaque handle. Reclaim it with `mm_channel_free`."""

_lib = ctypes.CDLL(str(_library_path()))

_lib.mm_channel_await_tick.argtypes = [MmChannel]
_lib.mm_channel_await_tick.restype = ctypes.c_int32
_lib.mm_channel_budget.argtypes = [MmChannel, ctypes.POINTER(ctypes.c_int64), ctypes.POINTER(ctypes.c_uint64)]
_lib.mm_channel_budget.restype = ctypes.c_int32
_lib.mm_channel_config.argtypes = [MmChannel]
_lib.mm_channel_config.restype = ctypes.POINTER(GameConfig)
_lib.mm_channel_handshake.argtypes = [MmChannel, ctypes.POINTER(ctypes.c_uint8)]
_lib.mm_channel_handshake.restype = ctypes.c_int32
_lib.mm_channel_open.argtypes = [ctypes.POINTER(ctypes.c_uint8), ctypes.c_int32]
_lib.mm_channel_open.restype = MmChannel
_lib.mm_channel_respond.argtypes = [MmChannel, ctypes.POINTER(FleetAction)]
_lib.mm_channel_respond.restype = ctypes.c_int32
_lib.mm_channel_state.argtypes = [MmChannel]
_lib.mm_channel_state.restype = ctypes.POINTER(GameState)
_lib.mm_corridor_clear.argtypes = [MmChannel, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float]
_lib.mm_corridor_clear.restype = ctypes.c_bool
_lib.mm_diff_degrees.argtypes = [ctypes.c_float, ctypes.c_float]
_lib.mm_diff_degrees.restype = ctypes.c_float
_lib.mm_disc_free.argtypes = [MmChannel, ctypes.c_float, ctypes.c_float, ctypes.c_float]
_lib.mm_disc_free.restype = ctypes.c_bool
_lib.mm_line_of_sight.argtypes = [MmChannel, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float]
_lib.mm_line_of_sight.restype = ctypes.c_bool
_lib.mm_navigate_to.argtypes = [MmChannel, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.POINTER(ctypes.c_float)]
_lib.mm_navigate_to.restype = None
_lib.mm_normalize_degrees.argtypes = [ctypes.c_float]
_lib.mm_normalize_degrees.restype = ctypes.c_float
_lib.mm_path_length.argtypes = [MmChannel, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float]
_lib.mm_path_length.restype = ctypes.c_float
_lib.mm_payload_pos.argtypes = [ctypes.c_float, ctypes.POINTER(ctypes.c_float)]
_lib.mm_payload_pos.restype = None
_lib.mm_point_free.argtypes = [MmChannel, ctypes.c_float, ctypes.c_float]
_lib.mm_point_free.restype = ctypes.c_bool
_lib.mm_point_seg_dist.argtypes = [ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float]
_lib.mm_point_seg_dist.restype = ctypes.c_float
_lib.mm_route_waypoints.argtypes = [MmChannel, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.POINTER(ctypes.c_float), ctypes.c_int32]
_lib.mm_route_waypoints.restype = ctypes.c_int32
_lib.mm_channel_free.argtypes = [MmChannel]
_lib.mm_channel_free.restype = None

def mm_channel_await_tick(ch: MmChannel) -> int:
    return _lib.mm_channel_await_tick(ch)

def mm_channel_budget(ch: MmChannel, out_remaining: ctypes._Pointer[ctypes.c_int64], out_last_charge: ctypes._Pointer[ctypes.c_uint64]) -> int:
    return _lib.mm_channel_budget(ch, out_remaining, out_last_charge)

def mm_channel_config(ch: MmChannel) -> ctypes._Pointer[GameConfig]:
    return _lib.mm_channel_config(ch)

def mm_channel_handshake(ch: MmChannel, out_team: ctypes._Pointer[ctypes.c_uint8]) -> int:
    return _lib.mm_channel_handshake(ch, out_team)

def mm_channel_open(path: ctypes._Pointer[ctypes.c_uint8], path_len: int) -> MmChannel:
    return _lib.mm_channel_open(path, path_len)

def mm_channel_respond(ch: MmChannel, action: ctypes._Pointer[FleetAction]) -> int:
    return _lib.mm_channel_respond(ch, action)

def mm_channel_state(ch: MmChannel) -> ctypes._Pointer[GameState]:
    return _lib.mm_channel_state(ch)

def mm_corridor_clear(ch: MmChannel, ax: float, ay: float, bx: float, by: float) -> bool:
    return _lib.mm_corridor_clear(ch, ax, ay, bx, by)

def mm_diff_degrees(a: float, b: float) -> float:
    return _lib.mm_diff_degrees(a, b)

def mm_disc_free(ch: MmChannel, x: float, y: float, radius: float) -> bool:
    return _lib.mm_disc_free(ch, x, y, radius)

def mm_line_of_sight(ch: MmChannel, ax: float, ay: float, bx: float, by: float) -> bool:
    return _lib.mm_line_of_sight(ch, ax, ay, bx, by)

def mm_navigate_to(ch: MmChannel, fx: float, fy: float, tx: float, ty: float, out: ctypes._Pointer[ctypes.c_float]) -> None:
    return _lib.mm_navigate_to(ch, fx, fy, tx, ty, out)

def mm_normalize_degrees(deg: float) -> float:
    return _lib.mm_normalize_degrees(deg)

def mm_path_length(ch: MmChannel, fx: float, fy: float, tx: float, ty: float) -> float:
    return _lib.mm_path_length(ch, fx, fy, tx, ty)

def mm_payload_pos(capture: float, out: ctypes._Pointer[ctypes.c_float]) -> None:
    return _lib.mm_payload_pos(capture, out)

def mm_point_free(ch: MmChannel, x: float, y: float) -> bool:
    return _lib.mm_point_free(ch, x, y)

def mm_point_seg_dist(px: float, py: float, ax: float, ay: float, bx: float, by: float) -> float:
    return _lib.mm_point_seg_dist(px, py, ax, ay, bx, by)

def mm_route_waypoints(ch: MmChannel, fx: float, fy: float, tx: float, ty: float, out: ctypes._Pointer[ctypes.c_float], cap: int) -> int:
    return _lib.mm_route_waypoints(ch, fx, fy, tx, ty, out, cap)

def mm_channel_free(handle: MmChannel) -> None:
    return _lib.mm_channel_free(handle)
